# Generated by Django 4.0.2 on 2023-03-12 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 21, 59, 40, 364682)),
        ),
    ]
